#lang racket/base
(provide prefixes-si)
(define prefixes-si
'((Y . yotta)
  (Z . zetta)
  (E . exa)
  (P . peta)
  (T . tera)
  (G . giga)
  (M . mega)
  (k . kilo)
  (h . hecto)
  (da . deca)
  (d . deci)
  (c . centi)
  (m . milli)
  (μ . micro)  ; "\u03BC"
  (µ . micro)  ; "\u00B5" FIXME this needs to be in a normalization pass
  (u . micro)
  (n . nano)
  (p . pico)
  (f . femto)
  (a . atto)
  (z . zepto)
  (y . yocto))
)
